### ISSUE TITLE
Custom music

### ISSUE THREAD

**Issue by ttoinou** [andrewhills/ShadertoyCustomTextures#1]
Hi,
First that's a great bookmarklet thank you ! I'm always using it :) 
I was wondering if this script could be adapted to put custom music input ?
Thx

**Comment by ahillss** [comment]
Thanks, glad someone is finding it useful. I'm not sure how easy it would be to implement this.

The main problem is what kind of audio files should it support, I don't think the web has builtin support for MP3s or other compresses formats (on all browsers and systems), and I don't want to include any libraries needed to play them.

**Comment by ttoinou** [comment]
WAV would be awesome already !

**Comment by ttoinou** [comment]
I'll look at it when I have the time I can understand the code

**Comment by ahillss** [comment]
That would be great if you could look it up, I'm bit too lazy at the moment to go digging.

**Comment by andrewhills** [comment]
Ok I figured out how to play music (including mp3s) and also video, just trying to figure how to differentiate between them now.

**Comment by ahillss** [comment]
Got it working for audio (including mp3 etc) and video, just fixing some bugs before I update it.

**Comment by ahillss** [comment]
Okay done!

I'll update the chrome and firefox extensions on their websites in a little while just to make sure there aren't any edge cases that I missed.
